apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-secret
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" . | nindent 4 }}
data:
  dockerhub-password: {{ default "" .Values.config.dockerhubPassword | b64enc | quote  }}